import './globals.css'
import Proivders from '@/components/Proivders'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Proivders>
      <body>
        {children}
      </body>
      </Proivders>
    </html>
  )
}
